Algoritmo "idade de uma pessoa"

Var
idade: inteiro
dias: inteiro
horas: inteiro
minutos: inteiro
segundos: inteiro
Inicio
      escreval (" digite sua idade: ")
      leia(idade)
      dias<-idade*365
      horas<-dias*24
      minutos<-horas*60
      segundos<-minutos*60

escreval ("dias: ",dias)
escreval ("horas: ",horas)
escreval ("minutos: ",minutos)
escreval ("segundos: ",segundos)



Fimalgoritmo